### ISSUE TITLE
Runner configuration, empty strings

### ISSUE THREAD

**Issue by danielsreichenbach** [bodsch/ansible-collection-scm#11]
I've been using this collection quite extensively over the months, and ran into an issue with the generation of the runner `config.yaml` recently.

It seems the template will never render empty strings, but this has an unwanted side effect.

## Example

```yaml
forgejo_runner_config:
    container:
        docker_host: ''
        force_pull: 'false'
```

As per the [runner installation documentation](https://forgejo.org/docs/latest/admin/runner-installation/#configuration) this will auto-select a docker host and auto-mount the Docker socket.

But since the string is empty, the template will not render `docker_host` at all, resulting in the runner defaulting to the config value of `-`, where the socket is not auto-mounted.

It seems some of the runner settings have meaning with empty values, so I am not sure what the proper fix would be.

As a workaround I currently opt to use

```yaml
forgejo_runner_config:
    container:
        docker_host: '-'
        valid_volumes: ['/var/run/docker.sock']
        force_pull: 'false'
```

Since `valid_volumes` is not handled as a list I also submitted #10 to resolve this.
