### ISSUE TITLE
Failure when updating an auth method with dash in id

### ISSUE THREAD

**Issue by rockdreamer** [bodsch/ansible-collection-scm#18]
Triggering condition: adding an LDAP (via BindDN) auth method called some-ldap

The output of `forgejo admin auth list` is not parsed because the inner_pattern regex in ForgejoAuth's auth_exists method cannot cope with the dash in the id.

Suggestion: add `"--vertical-bars"` to the args_list and change the inner_pattern regex to something like

```
inner_pattern = re.compile(r"(?P<ID>\d+)\s+\|(?P<name>[\w_-]+)\s+\|(?P<type>[a-zA-Z+_\-\(\ \)\.]+)\s+\|(?P<enabled>\w+)", flags=re.MULTILINE | re.DOTALL)
```

**Comment by bodsch** [comment]
An example would be helpful for me.

**Comment by rockdreamer** [comment]
Of course! I tried running this role with a configuration that looks like this.

```yaml
forgejo_auths:
  ldap:
    state: "present"
    name: "euwest1-ldap"
    active: true
    security_protocol: "LDAPS"
    skip_tls_verify: false
    hostname: "xxxxxxxx"
    port: "zzzz"
    user_search_base: "ou=users,dc=foo"
    filters:
      user: "(uid=%s)"

```

The problem is that the inner regex only allows `\w` for `name`. Therefore it doesn't match the - in `euwest1-ldap`. As a consequence, the code thinks that the auth is not present and tries to recreate it. But the creation command fails because euwest1-ldap is actually there!

I've got fixes for this and other issues I'm raising in [another branch](https://github.com/bodsch/ansible-collection-scm/compare/main...rockdreamer:ansible-collection-scm:dashes_in_ids). I'll deal with the first PR first though :)
